services:
  backintime-sshd:
    image: caco3x/backintime-sshd
    environment:
      # Username of the user on the remote host
      # If you change it, make sure to also update it on the volume mount!
      - USERNAME=backintime
      # Public SSH key of the user
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7osnqdNQeyf8Qqh1xkfX0QJbYhft8x9XQD7k8crQrFfK4QGu3DRSdFpsku2ekAqrczpcOcgDyx1Uu8Ug8EWfIotGAqXDtWcM2r59HJBMKSYxkjxza1JUwGIIZu6T5qvcIZylXI5yfC1Xn8nsrEneJVp65lCf1bfzT4VARVIUR1lV1n5QvhI7U1duw3SBVsgFt2HPOBJo/bH019VwQqP226cCvTNuGiJi2zc8eyFrJGPuYNv/THSnaJLIRoYlJUI6GsQ2fMgzjSlbV7Q0sJ7qphVjlHj228MkKgP76ntDlSNZ0qFAaXxVYOQ2THz2F4anJxnwnL4kXkQ5n5bb0O9QywPYL249USLfJsl1T6ujytbzNWUpq2RNU15qoETvddc3+9o9ApIg/jgQ+eipK6Hi49DXspne/E74v3ybpiVU4XWFBrXlAUf0ipOfJE/Azr0+S0i9cS7NRjvlqOOA9hasqCUQaKAryRgJED/vJp0Lkcvv+pMYANVurwmZGzQZNAtc= root@PC3
    ports:
      - 10022:22
    restart: unless-stopped
    volumes:
      - ./ssh:/etc/ssh
      - /etc/passwd:/passwd:ro
      # Map the backup files into the folder "backintime" of the user "backintime" 
      # This is crutial since the backup data else only is stored in the docker container and gets lost once you delete it!
      - /volume1/backintime:/home/backintime/backintime
  